[package]
name = "recho"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.11.5"
lazy_static = "1.5.0"
serde = { version = "1.0.210", features = ["derive"] }
config = "0.14.0"

