[http]
port = 80

[https]
port = 443
private_key_file = "config/key.pem"
certificate_chain_file = "config/cert.pem"

[grpc]
port = 5001

[grpc.TLS]
port = 5002
private_key_file = "config/key.pem"
certificate_chain_file = "config/cert.pem"

[enable]
host = true
http = true
request = true
header = true
environment = true
file = true
https = true
grpc = true
grpc_tls = true

[metrics]
port = 9091
